#[alexxy]

#sync-uri = http://gentoo-mirror.alexxy.name/releases/amd64/binpackages/17.1/x86-64/

# https://gentoo-mirror.alexxy.name/releases/amd64/binpackages/
#					     releases/amd64/binpackages/
